export const metadata = {
  title: "الشروط والأحكام - كابيتال جيت",
  description: "تعرف على شروط استخدامك لمنصة كابيتال جيت.",
  keywords: [
    "الشروط والأحكام",
    "الخصوصية",
    "البيانات الشخصية",
    "مشروعات عقارية",
    "مشاريع سكنية",
    "عقارات التجمع الخامس",
    "شقق العاصمة الإدارية",
    " فيلات الشيخ زايد",
    " الساحل الشمالي",
    "شركة عقارات مصر",
    "كابيتال جيت",
    "شراء شقة",
    "الاستثمار العقاري",
    "وسيط عقاري",
    "مشروعات مصر العقارية",
    "عقارات فاخرة",
    "الشروط",
    "الأحكام",
    "سياسة الاستخدام",
  ],
  viewport: 'width=device-width, initial-scale=1.0',
  openGraph: {
    title: "الشروط والأحكام - كابيتال جيت",
    description: "تعرف على شروط استخدامك لمنصة كابيتال جيت.",
    images: [
      {
        url: "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
        width: 1200,
        height: 630,
        alt: "الشروط والأحكام - كابيتال جيت",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "الشروط والأحكام - كابيتال جيت",
    description: "تعرف على شروط استخدامك لمنصة كابيتال جيت.",
    images: [
      "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
    ],
  },
};
