export const metadata = {
  title: "Terms and Conditions - Capital Gate",
  description: "Learn about the terms and conditions of using Capital Gate.",
  keywords: [
    "about capital gate",
    "real estate",
    "vision",
    "mission",
    "New Cairo properties",
    "New Capital apartments",
    "Sheikh Zayed villas",
    "North Coast real estate",
    "Egypt property broker",
    "Capital Gate Real Estate",
    "buy apartment in Egypt",
    "real estate investment",
    "trusted real estate agency",
    "luxury properties Egypt",
    "real estate developers",
    "capital gate",
    "property developers",
    "Terms and Conditions",
    "capital gate",
    "data privacy",
    "personal information",
    "terms",
    "conditions",
    "usage policy",
  ],
  viewport: 'width=device-width, initial-scale=1.0',
  openGraph: {
    title: "Terms and Conditions - Capital Gate",
    description: "Learn about the terms and conditions of using Capital Gate.",
    images: [
      {
        url: "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
        width: 1200,
        height: 630,
        alt: "Terms and Conditions - Capital Gate",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms and Conditions - Capital Gate",
    description: "Learn about the terms and conditions of using Capital Gate.",
    images: [
      "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
    ],
  },
};
