export const metadata = {
  title: "Privacy Policy - Capital Gate",
  description: "Learn how we handle your data and privacy.",
  keywords: [
    "about capital gate",
    "real estate",
    "vision",
    "mission",
    "New Cairo properties",
    "New Capital apartments",
    "Sheikh Zayed villas",
    "North Coast real estate",
    "Egypt property broker",
    "Capital Gate Real Estate",
    "buy apartment in Egypt",
    "real estate investment",
    "trusted real estate agency",
    "luxury properties Egypt",
    "real estate developers",
    "capital gate",
    "property developers",
    "privacy policy",
    "capital gate",
    "data privacy",
    "personal information",
  ],
  openGraph: {
    title: "Privacy Policy - Capital Gate",
    description: "Learn how we handle your data and privacy.",
    images: [
      {
        url: "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
        width: 1200,
        height: 630,
        alt: "Privacy Policy - Capital Gate",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy - Capital Gate",
    description: "Learn how we handle your data and privacy.",
    viewport: 'width=device-width, initial-scale=1.0',
    images: [
      "https://res.cloudinary.com/dfltsy2ov/image/upload/v1753623051/logo/sxdinb9u5qqkth3ewals.avif",
    ],
  },
};
